_target_: topobench.model.TBModel

model_name: hopse_m
model_domain: cell

feature_encoder:
  _target_: topobench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: SANNFeatureEncoder
  dataset_in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  in_channels: ${transforms.sann_encoding.in_channels} 
  max_hop: ${transforms.sann_encoding.max_hop}
  out_channels: 64
  proj_dropout: 0.0
  selected_dimensions:
    - 0
    - 1
    - 2
  feature_lifting: Duplicate
  all_ones: true

backbone:
  _target_: topobench.nn.backbones.simplicial.sann.SANN
  in_channels: ${model.backbone.hidden_channels}
  n_layers: 2
  max_hop: ${transforms.sann_encoding.max_hop} 
  hidden_channels: ${model.feature_encoder.out_channels}
  update_func: "lrelu"

backbone_wrapper:
  _target_: topobench.nn.wrappers.SANNWrapper
  _partial_: true
  wrapper_name: SANNWrapper
  out_channels: ${model.feature_encoder.out_channels}
  complex_dim: ${transforms.sann_encoding.max_rank}
  max_hop: ${transforms.sann_encoding.max_hop}
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

readout:
  _target_: topobench.nn.readouts.${model.readout.readout_name}
  readout_name: SANNReadout  #  Use <NoReadOut> in case readout is not needed Options: PropagateSignalDown
  max_hop: ${transforms.sann_encoding.max_hop}
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}} # The highest order of cell dimensions to consider
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum
  complex_dim: ${transforms.sann_encoding.max_rank}

# compile model for faster training with pytorch 2.0
compile: false