# USE python -m topobench transforms.one_hot_node_degree_features.degrees_fields=x to run this config
defaults:
  - data_manipulations@one_hot_node_degree_features: one_hot_node_degree_features # Here we use the one_hot_node_degree_features to one-hot atoms types.
  - liftings@_here_: ${get_required_lifting:graph,${model}}
  
one_hot_node_degree_features: 
  degrees_field: x
  features_field: x