defaults:
  - data_manipulations@redefine_simplicial_neighborhoods: redefine_simplicial_neighborhoods
  - data_manipulations@sann_encoding: add_gpse_information

redefine_simplicial_neighbourhoods:
  signed: True