_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "SimplicialGraphInducedLifting"
complex_dim: ${oc.select:dataset.parameters.max_dim_if_lifted,2}
preserve_edge_attr: False
signed: True
feature_lifting: ProjectionSum
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}

