_target_: topobench.models.base_model.BaseModel

backbone:
  _target_: topobench.nn.backbones.hypergraph.hypergraph_convolution.HyperGraphConvolution
  a: 16
  b: 8
  reapproximate: False
  cuda: 0

loss:
 _target_: torch.nn.CrossEntropyLoss
