_target_: topobench.loss.TBLoss

dataset_loss:
  task: ${dataset.parameters.task}
  loss_type: ${dataset.parameters.loss_type}
  focal_gamma: ${oc.select:dataset.parameters.focal_gamma,2.0}
  focal_alpha: ${oc.select:dataset.parameters.focal_alpha,null}

modules_losses: # Collect model losses
  feature_encoder: ${oc.select:model.feature_encoder.loss,null}
  backbone: ${oc.select:model.backbone.loss,null}
  readout: ${oc.select:model.readout.loss,null}