transform_name: "KeepSelectedDataFields"
transform_type: "data manipulation"
# Native graph fields kept by the transform.
base_fields: ["x", "edge_index", "edge_attr", "pos", "y", "batch", "train_mask", "val_mask", "test_mask"]
preserved_fields: []
