_target_: topobenchmark.transforms.data_transform.DataTransform
transform_name: "DerivePS"
transform_type: "data manipulation"
ps_types: ['RWSE', 'ElstaticPE', 'LapPE', 'HKdiagSE', 'CycleGE']

# LapPE config
laplacian_norm_type: 'sym'
posenc_LapPE_eigen_max_freqs: 10
posenc_LapPE_eigen_eigvec_norm: 'L2'
posenc_LapPE_eigen_skip_zero_freq: True
posenc_LapPE_eigen_eigvec_abs: True

# RWSE config
kernel_param_times: [2,30]

