_target_: topobench.evaluator.evaluator.TBEvaluator
task: ${dataset.parameters.task}
task_level: ${dataset.parameters.task_level}
num_classes: ${dataset.parameters.num_classes}

# Metrics
metrics:  [accuracy, precision, recall, auroc, "f1_score", "average_precision", "cohen_kappa", "mcc", "jaccard"] # Available options: accuracy, auroc, precision, recall