defaults:
  # - data_manipulations: node_degrees
  # - data_manipulations@one_hot_node_degree_features: one_hot_node_degree_features
  # - liftings@_here_: graph2cell_default
  - data_manipulations@redefine_simplicial_neighbourhoods: redefine_simplicial_neighbourhoods
  - data_manipulations@sann_encoding: hopse_ps_information

redefine_simplicial_neighbourhoods:
  neighborhoods: ['up_adjacency-0', 'down_incidence-1', 'down_incidence-2'] #${transforms.sann_encoding.neighborhoods,null}
  signed: True

  