defaults:
  - data_manipulations@barycentric_subdivision: barycentric_subdivision

barycentric_subdivision:
  signed: False


#-------
# defaults:
#   - data_manipulations@node_degrees: node_degrees
#   # - data_manipulations@one_hot_1: one_hot_node_degree_features
#   # - data_manipulations@one_hot_2: one_hot_node_degree_features
#   # - data_manipulations@one_hot_3: one_hot_node_degree_features
#   #- liftings@_here_: ${get_required_lifting:graph,${model}}

# node_degrees:
#   selected_fields: ["incidence_1", "incidence_2", "incidence_2"] # "incidence"
#   degrees_types: ["up_cell_degree", "up_cell_degree", "down_cell_degree"] # "up_cell_degree", "down_cell_degree"
#   stat_vars: [ "0_cell_degrees_up", "1_cell_degrees_up", "2_cell_degrees_down"]

# one_hot_1:
#   degrees_field: "0_cell_degrees_up"
#   features_field: "x_0"
#   max_degree: 9

# one_hot_2:
#   degrees_field: "1_cell_degrees_up"
#   features_field: "x_1"
#   max_degree: 2

# one_hot_3:
#   degrees_field: "2_cell_degrees_down"
#   features_field: "x_2"
#   max_degree: 3

