defaults:
  - data_manipulations@redefine_simplicial_neighbourhoods: redefine_simplicial_neighbourhoods
  - data_manipulations@sann_encoding: add_gpse_information

redefine_simplicial_neighbourhoods:
  signed: True