defaults:
  # - data_manipulations: node_degrees
  # - data_manipulations@one_hot_node_degree_features: one_hot_node_degree_features
  - liftings@_here_: no_lifting
  - data_manipulations@sann_encoding: hopse_ps_information