defaults:
  - data_manipulations@barycentric_subdivision: barycentric_subdivision
  - data_manipulations@redefine_simplicial_neighborhoods: redefine_simplicial_neighborhoods
  - data_manipulations@sann_encoding: hopse_ps_information

barycentric_subdivision:
  signed: True
  subdivide_ranks: [2]
  apply_to: ["test"]

redefine_simplicial_neighborhoods:
  signed: True

sann_encoding:
  pe_types: 
    - 'RWSE' 
    - 'ElstaticPE'
    - 'HKdiagSE'
    - 'LapPE'
   

  # Different PS have different sizes, need to unify them. 
  target_pe_dim: 20

  # LapPE config
  laplacian_norm_type: 'sym'
  posenc_LapPE_eigen_max_freqs: 18
  posenc_LapPE_eigen_eigvec_norm: 'L2'
  posenc_LapPE_eigen_skip_zero_freq: True
  posenc_LapPE_eigen_eigvec_abs: True

  # RWSE config
  kernel_param_RWSE: 
    - 2
    - 20


  # HKdiagSE config
  kernel_param_HKdiagSE: 
    - 1
    - 22