defaults:
  - data_manipulations@node_degrees: node_degrees
  - data_manipulations@one_hot_1: one_hot_node_degree_features
  - data_manipulations@one_hot_2: one_hot_node_degree_features
  - data_manipulations@one_hot_3: one_hot_node_degree_features
  #- liftings@_here_: ${get_required_lifting:graph,${model}}

node_degrees:
  selected_fields: ["incidence_1", "incidence_2", "incidence_2"] # "incidence"
  degrees_types: ["up_cell_degree", "up_cell_degree", "down_cell_degree"] # "up_cell_degree", "down_cell_degree"
  stat_vars: [ "0_cell_degrees_up", "1_cell_degrees_up", "2_cell_degrees_down"]

one_hot_1:
  features_fields: "0_cell_degrees_up"
  max_degree: 100

one_hot_2:
  features_fields: "1_cell_degrees_up"
  max_degree: 100

one_hot_3:
  features_fields: "2_cell_degrees_up"
  max_degree: 100