defaults:
  #- /transforms/data_manipulations@tree: decision_tree #infere_tree
  - /transforms/data_manipulations@get_graph: infere_knn_connectivity_sklearn 

get_graph:
  fit_key: "x"
  query_key: "x"
  n_neighbors: 15