_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "ExpanderGraphLifting"
node_degree: 2
k_value: 1
complex_dim: 1
feature_lifting: ProjectionSum
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}

