_target_: topobenchmarkx.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "HypergraphKHopLifting"
complex_dim: 1
k_value: 1
feature_lifting: ProjectionSum
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}