transform_type: 'lifting'
transform_name: "HypergraphKHopLifting"
k_value: 1
feature_lifting: ProjectionSum
# Required for all liftings to make the pipeline executable 
preserve_edge_attr: False
complex_dim: 0
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}