# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.Timer.html

model_timer:
  _target_: topobenchmarkx.callbacks.timer_callback.PipelineTimer #lightning.pytorch.callbacks.Timer
