#!/usr/bin/env bash

# Define log files
LOG_FILE="scripts/script_output.log"
ERROR_LOG_FILE="scripts/script_error.log"
FAILED_LOG_FILE="scripts/failed_runs.log"

# Clear previous log files
> "$LOG_FILE"
> "$ERROR_LOG_FILE"
> "$FAILED_LOG_FILE"

# Function to run a command and check for failure
run_command() {
	local cmd="$1"
	# Run the command and capture the output and error
	{ eval "$cmd" 2>&1 | tee -a "$LOG_FILE"; } 2>> "$ERROR_LOG_FILE"
	# Check if the command failed
	if [ ${PIPESTATUS[0]} -ne 0 ]; then
		echo "Command failed: $cmd" >> "$FAILED_LOG_FILE"
		echo "Check $ERROR_LOG_FILE for details." >> "$FAILED_LOG_FILE"
	fi
}

commands=(
# mantra_name
'python -m topobench dataset=simplicial/mantra_name model=simplicial/hopse_g transforms.sann_encoding.max_hop=2 transforms.sann_encoding.max_rank=2 transforms.sann_encoding.neighborhoods=['up_adjacency-0'] transforms.sann_encoding.pretrain_model=PCQM4MV2 model.feature_encoder.proj_dropout=0.25 model.backbone.n_layers=1 model.backbone.hidden_channels=256 model.readout.hidden_dim=256 model.feature_encoder.out_channels=256 model.readout.readout_name=SANNReadout optimizer.parameters.weight_decay=0.0 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=256 dataset.loader.parameters.manifold_dim=2 transforms.sann_encoding.copy_initial=True transforms.redefine_simplicial_neighborhoods.signed=True transforms.redefine_simplicial_neighborhoods.complex_dim=3  transforms.sann_encoding.copy_initial=True transforms.redefine_simplicial_neighborhoods.neighborhoods=['up_adjacency-0'] transforms.redefine_simplicial_neighborhoods.signed=True dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["HOPSE_GPSE","simplicial"] logger.wandb.project=HOPSE_reproducibility --multirun' # HOPSE_GPSE,MANTRA_name,simplicial
'python -m topobench dataset=simplicial/mantra_name model=simplicial/scn model.feature_encoder.proj_dropout=0.25 model.backbone.n_layers=4 model.readout.hidden_dim=128 model.feature_encoder.out_channels=128 model.readout.readout_name=PropagateSignalDown optimizer.parameters.weight_decay=0.0001 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=128 dataset.loader.parameters.manifold_dim=2   dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["scn","simplicial"] logger.wandb.project=HOPSE_reproducibility --multirun' # scn,MANTRA_name,simplicial
'python -m topobench dataset=simplicial/mantra_name model=simplicial/hopse_m transforms.sann_encoding.max_hop=4 transforms.sann_encoding.max_rank=2 transforms.sann_encoding.neighborhoods=['up_adjacency-0','up_adjacency-1','2-up_adjacency-0','down_adjacency-1','down_adjacency-2','2-down_adjacency-2'] model.feature_encoder.proj_dropout=0.25 model.backbone.n_layers=1 model.backbone.hidden_channels=128 model.readout.hidden_dim=128 model.feature_encoder.out_channels=128 model.readout.readout_name=SANNReadout optimizer.parameters.weight_decay=0.0 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=256 dataset.loader.parameters.manifold_dim=2 transforms.sann_encoding.copy_initial=True transforms.sann_encoding.is_undirected=True transforms.redefine_simplicial_neighborhoods.signed=True transforms.redefine_simplicial_neighborhoods.complex_dim=3  transforms.redefine_simplicial_neighborhoods.neighborhoods=['up_adjacency-0','up_adjacency-1','2-up_adjacency-0','down_adjacency-1','down_adjacency-2','2-down_adjacency-2'] transforms.redefine_simplicial_neighborhoods.signed=True dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["HOPSE_MANUAL_PE","simplicial"] logger.wandb.project=HOPSE_reproducibility --multirun' # HOPSE_MANUAL_PE,MANTRA_name,simplicial
'python -m topobench dataset=simplicial/mantra_name model=simplicial/sccnn_custom model.feature_encoder.proj_dropout=0.25 model.backbone.n_layers=4 model.readout.hidden_dim=64 model.feature_encoder.out_channels=64 model.backbone.sc_order=3 model.backbone.conv_order=1 model.readout.readout_name=PropagateSignalDown optimizer.parameters.weight_decay=0.0 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=256 dataset.loader.parameters.manifold_dim=2   dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["sccnn","simplicial"] logger.wandb.project=HOPSE_reproducibility --multirun' # sccnn,MANTRA_name,simplicial
'python -m topobench dataset=simplicial/mantra_name model=simplicial/sann transforms.sann_encoding.max_hop=3 transforms.sann_encoding.max_rank=2 transforms.sann_encoding.complex_dim=3 model.feature_encoder.proj_dropout=0.5 model.backbone.n_layers=4 model.backbone.hidden_channels=128 model.readout.hidden_dim=128 model.feature_encoder.out_channels=128 model.readout.readout_name=SANNReadout optimizer.parameters.weight_decay=0.0 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=128 dataset.loader.parameters.manifold_dim=2 transforms.sann_encoding.use_initial_features=True   dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["SANN","simplicial"] logger.wandb.project=HOPSE_reproducibility --multirun' # SANN,MANTRA_name,simplicial
'python -m topobench dataset=simplicial/mantra_name model=graph/gat model.feature_encoder.proj_dropout=0.25 model.backbone.hidden_channels=32 model.readout.hidden_dim=32 model.feature_encoder.out_channels=32 model.readout.readout_name=NoReadOut optimizer.parameters.weight_decay=0.0001 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=256 dataset.loader.parameters.manifold_dim=2   dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["gat","graph"] logger.wandb.project=HOPSE_reproducibility --multirun' # gat,MANTRA_name,simplicial
'python -m topobench dataset=simplicial/mantra_name model=graph/gin model.feature_encoder.proj_dropout=0.25 model.backbone.hidden_channels=32 model.readout.hidden_dim=32 model.feature_encoder.out_channels=32 model.readout.readout_name=NoReadOut optimizer.parameters.weight_decay=0.0 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=256 dataset.loader.parameters.manifold_dim=2   dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["gin","graph"] logger.wandb.project=HOPSE_reproducibility --multirun' # gin,MANTRA_name,simplicial
'python -m topobench dataset=simplicial/mantra_name model=graph/gcn model.feature_encoder.proj_dropout=0.25 model.backbone.hidden_channels=32 model.readout.hidden_dim=32 model.feature_encoder.out_channels=32 model.readout.readout_name=NoReadOut optimizer.parameters.weight_decay=0.0 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=128 dataset.loader.parameters.manifold_dim=2   dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["gcn","graph"] logger.wandb.project=HOPSE_reproducibility --multirun' # gcn,MANTRA_name,simplicial
'python -m topobench dataset=simplicial/mantra_name model=simplicial/topotune model.feature_encoder.proj_dropout=0.25 model.readout.hidden_dim=128 model.feature_encoder.out_channels=128 model.readout.readout_name=PropagateSignalDown model.backbone.GNN.num_layers=4 model.backbone.neighborhoods=['up_adjacency-0','up_adjacency-1','2-up_adjacency-0','down_adjacency-1','down_adjacency-2','2-down_adjacency-2'] optimizer.parameters.weight_decay=0.0 optimizer.parameters.lr=0.001 dataset.dataloader_params.batch_size=256 dataset.loader.parameters.manifold_dim=2  model.tune_gnn=GIN transforms.redefine_simplicial_neighborhoods.signed=True dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=250 trainer.check_val_every_n_epoch=5 trainer.devices=\[1\] callbacks.early_stopping.patience=10 logger.wandb.tags=["topotune","simplicial"] logger.wandb.project=HOPSE_reproducibility --multirun' # topotune,MANTRA_name,simplicial
)

# Iterate over the commands and run them
for cmd in "${commands[@]}"; do
	echo "Running: $cmd"
	run_command "$cmd"
done
