# Dataset loader config
loader:
 _target_: topobenchmark.data.loaders.H36MDatasetLoader
 parameters: 
   data_domain: graph
   data_type: motion
   data_name: H36MDataset
   data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
   keep_splits_on_disk: false # True loads faster, but runs slower

# Dataset parameters
parameters:
 num_features: 1 # one feature per node
 num_classes: 1 # number of output features per node
 task: regression
 loss_type: mse
 monitor_metric: mae
 task_level: node
 metrics:
  - mae
  - mpjpe

# Splits configuration
split_params:
 learning_setting: inductive
 split_type: fixed

# Dataloader parameters
dataloader_params:
 batch_size: 256 #1       # Fixed
 num_workers: 8
 pin_memory: false


visualization:
  _target_: topobenchmark.callbacks.visualization.MotionVisualizationCallback
  num_samples: 1