# Dataset loader config
loader:
  _target_: topobench.data.loaders.SyntheticGraphDatasetLoader
  parameters:
    data_domain: graph
    data_type: synthetic
    data_name: SyntheticNodeGraph
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    seed: ${seed}

# Dataset parameters
parameters:
  num_features: 4
  num_classes: 2
  num_nodes: 18
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node

# Splits
split_params:
  learning_setting: transductive
  split_type: fixed

# Dataloader parameters
dataloader_params:
  batch_size: 1
  num_workers: 0
  pin_memory: False
