# Dataset loader config
loader:
  _target_: topobench.data.loaders.SyntheticGraphDatasetLoader
  parameters:
    data_domain: graph
    data_type: synthetic
    data_name: SyntheticGraph
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    seed: ${seed}

# Dataset parameters
parameters:
  num_features: 4
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph

# Splits
split_params:
  learning_setting: inductive
  split_type: fixed

# Dataloader parameters
dataloader_params:
  batch_size: 4
  num_workers: 0
  pin_memory: False
