_target_: topobench.model.TBModel

model_name: mlp
model_domain: non_relational

feature_encoder:
  _target_: topobench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: FlatEncoder
  in_channels: ${dataset.parameters.num_features}
  out_channels: ${get_flattened_feature_matrix_dim:${dataset.parameters.num_nodes},${dataset.parameters.num_features}}

backbone:
  _target_: topobench.nn.backbones.MLP
  in_channels: ${model.feature_encoder.out_channels}
  hidden_channels: [128, 64, 32]
  out_channels: ${get_flattened_out_channels:${dataset.parameters.num_nodes},${dataset.parameters.num_classes}}
  dropout: 0.25
  norm: null
  norm_kwargs: null
  act: relu
  act_kwargs: null
  final_act: null
  final_act_kwargs: null
  num_nodes: ${oc.select:dataset.parameters.num_nodes,null}

readout:
  _target_: topobench.nn.readouts.${model.readout.readout_name}
  readout_name: NoReadOut
  hidden_dim: ${model.backbone.out_channels}
  out_channels: ${model.backbone.out_channels}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum
  logits_linear_layer: false


# compile model for faster training with pytorch 2.0
compile: false
