data_domain: hypergraph
data_type: interaction
data_name: senate_committee
data_dir: datasets/${data_domain}/${data_type}
#data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${data_name}

# Dataset parameters
num_nodes: 282
num_hyperedges: 315
num_classes: 2
max_dim: 2
task: classification