_target_: topobench.model.TBModel

model_name: GFT
model_domain: graph

feature_encoder:
  _target_: topobench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  out_channels: 64
  proj_dropout: 0.0

backbone:
  _target_: topobench.nn.backbones.GFT
  in_channels: ${model.feature_encoder.out_channels}
  hidden_channels: ${model.feature_encoder.out_channels}
  out_channels: ${model.feature_encoder.out_channels}
  num_layers: 2
  backbone: sage
  normalize: batch
  dropout: 0.15
  activation: relu
  tree_depth: 2
  codebook_size: 128
  codebook_heads: 4
  code_dim: ${model.feature_encoder.out_channels}
  use_cosine_sim: true
  learnable_codebook: true

backbone_wrapper:
  _target_: topobench.nn.wrappers.${model.backbone_wrapper.wrapper_name}
  _partial_: true
  wrapper_name: GNNWrapper
  out_channels: ${model.feature_encoder.out_channels}
  residual_connections: false
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

readout:
  _target_: topobench.nn.readouts.${model.readout.readout_name}
  readout_name: MLPReadout
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}
  in_channels: ${model.feature_encoder.out_channels}
  hidden_layers: [32]
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${define_task_level:${dataset.parameters.task_level},${dataset.split_params.learning_setting}}
  pooling_type: sum
  dropout: 0.2
  act: relu
  norm: null
  final_act: null

compile: false
