# configs/model/graph/graphgps.yaml
_target_: topobench.model.TBModel

model_name: GraphGPS       
model_domain: graph

feature_encoder:
  _target_: topobench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  out_channels: 64                
  proj_dropout: 0.0

backbone:
  _target_: topobench.nn.backbones.graph.graphgps.GraphGPSNetwork
  num_layers: 4
  in_channels: 21
  hidden_channels: ${model.feature_encoder.out_channels}
  local_gnn_type: GINE
  global_model_type: Transformer
  num_heads: 8
  act: relu
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: false
  batch_norm: true
  equivstable_pe: false


backbone_wrapper:
  _target_: topobench.nn.wrappers.graph.graphgps_wrapper.GraphGPSWrapper
  _partial_: true
  wrapper_name: GraphMLPWrapper
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

# ─────────────────── Read-out head ─────────────────────
readout:
  _target_: topobench.nn.readouts.NoReadOut
  readout_name: NoReadOut           # set another readout if needed
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum

compile: false

