_target_: topobench.model.TBModel

model_name: graph_mlp
model_domain: graph

feature_encoder:
  _target_: topobench.nn.encoders.GraphNodeFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  out_channels: 32
  dropout: 0.0
  encoding_mode: ${oc.select:dataset.parameters.feature_encoding,continuous}
  categorical_cardinalities: ${oc.select:dataset.parameters.feature_cardinalities,null}

backbone:
  _target_: topobench.nn.backbones.GraphMLP
  in_channels: ${model.feature_encoder.out_channels}
  hidden_channels: ${model.feature_encoder.out_channels}
  dropout: 0.0
  loss:
    _target_: topobench.loss.model.GraphMLPLoss
    r_adj_power: 2
    tau: 1.0
    loss_weight: 0.5

backbone_wrapper:
  _target_: topobench.nn.wrappers.GraphMLPWrapper
  _partial_: true
  edge_attr_mode: ${validated_edge_attr_mode:${dataset},${model.model_name}}
  edge_weight_mode: ${validated_edge_weight_mode:${dataset},${model.model_name}}

readout:
  _target_: topobench.nn.readouts.NoReadOut
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${define_task_level:${dataset.parameters.task_level},${dataset.split_params.learning_setting}}
  pooling_type: sum

compile: false
