_target_: topobench.model.TBModel

model_name: nsd
model_domain: graph

feature_encoder:
  _target_: topobench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}} 
  out_channels: 32
  proj_dropout: 0.0

backbone:
  _target_: topobench.nn.backbones.NSD
  input_dim: ${model.feature_encoder.out_channels}
  hidden_dim: ${model.feature_encoder.out_channels}
  output_dim: ${model.feature_encoder.out_channels}
  num_layers: 2
  pe_dim: 10 # Keep at 10! Bit of a clumsy solution for now.
  pe_norm: false
  pe_type: None # laplacian, degree, rwse or None
  dropout: 0.2
  sheaf_type: diag # diag or bundle
  d: 3 # 2 or 3
  input_dropout: 0.0

backbone_wrapper:
  _target_: topobench.nn.wrappers.GNNWrapperWithPE 
  _partial_: true
  wrapper_name: GNNWrapperWithPE
  pe_type: ${model.backbone.pe_type}
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

readout:
  _target_: topobench.nn.readouts.${model.readout.readout_name}
  readout_name: NoReadOut #  Use <NoReadOut> in case readout is not needed Options: PropagateSignalDown
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}} # The highest order of cell dimensions to consider
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum

# compile model for faster training with pytorch 2.0
compile: false

